### ISSUE TITLE
Problem loading assets

### ISSUE THREAD

**Issue by bitmammoth** [Grumoth/godot-character-creator#2]
I'm getting a fatal error where godot hangs and then crashes during the loading of the assets. It outputs this error. The files seem to be there so I'm not sure what would cause this. 

***This is on Windows 10***

Godot Engine v3.2.beta.custom_build.ff58030ed
OpenGL ES 3.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE2

ERROR: Cannot open file 'res://.import/MainRig.gltf-a994b333ddf37bbec0e66ad9a1a12c7f.scn'.
   At: core\io\resource_format_binary.cpp:986
ERROR: Failed loading resource: res://.import/MainRig.gltf-a994b333ddf37bbec0e66ad9a1a12c7f.scn.
   At: core\io\resource_loader.cpp:278
ERROR: Failed loading resource: res://MainCharacter/Mesh/MainRig.gltf.
   At: core\io\resource_loader.cpp:278
ERROR: Cannot open file 'res://.import/MainRig.gltf-a994b333ddf37bbec0e66ad9a1a12c7f.scn'.
   At: core\io\resource_format_binary.cpp:986
ERROR: Failed loading resource: res://.import/MainRig.gltf-a994b333ddf37bbec0e66ad9a1a12c7f.scn.
   At: core\io\resource_loader.cpp:278
ERROR: Failed loading resource: res://MainCharacter/Mesh/MainRig.gltf.
   At: core\io\resource_loader.cpp:278
WARNING: _parse_ext_resource: Couldn't load external resource: res://MainCharacter/Mesh/MainRig.gltf
     At: scene\resources\resource_format_text.cpp:175

***On Linux 18.04lts It Loads***

**Comment by Grumoth** [comment]
Hi, have you tried with the stable 3.2 release version? I can't reproduce it that as I don't have Windows in my system, but it should work actually . I'm not sure what it coud be.. :/

**Comment by Grumoth** [comment]
Have you tried to re-export the MainRig.gltf from Blender?

**Comment by Grumoth** [comment]
Finally managed to reproduce and fix it, there was a lot of changes regarding gltf import structure and bone naming. Hope it works now.

**Comment by bitmammoth** [comment]
I apologize for not replying sooner I didn't see the update but can confirm that this loads on windows 10 now. There's a few errors that show up when running but I will create a separate issue for that. Looks very nice!
