### ISSUE TITLE
loading problem

### ISSUE THREAD

**Issue by DattaSwami** [Grumoth/godot-character-creator#3]
Windows 10 loading prblem
Godot Engine v3.2.beta.custom_build.ff58030ed
OpenGL ES 3.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
the error is showing
ERROR: Cannot open file 'res://.import/MainRig.gltf-a994b333ddf37bbec0e66ad9a1a12c7f.scn'.
At: core\io\resource_format_binary.cpp:986
ERROR: Failed loading resource: res://.import/MainRig.gltf-a994b333ddf37bbec0e66ad9a1a12c7f.scn.
At: core\io\resource_loader.cpp:278
ERROR: Failed loading resource: res://MainCharacter/Mesh/MainRig.gltf.
At: core\io\resource_loader.cpp:278
ERROR: Cannot open file 'res://.import/MainRig.gltf-a994b333ddf37bbec0e66ad9a1a12c7f.scn'.
At: core\io\resource_format_binary.cpp:986
ERROR: Failed loading resource: res://.import/MainRig.gltf-a994b333ddf37bbec0e66ad9a1a12c7f.scn.
At: core\io\resource_loader.cpp:278
ERROR: Failed loading resource: res://MainCharacter/Mesh/MainRig.gltf.
At: core\io\resource_loader.cpp:278
WARNING: _parse_ext_resource: Couldn't load external resource: res://MainCharacter/Mesh/MainRig.gltf
At: scene\resources\resource_format_text.cpp:175

**Comment by Grumoth** [comment]
Hi, have you tried with the stable 3.2 version? There's another issue commenting that and as I don't have windows I can't reproduce it. Have you tried to re-export from Blender?

**Comment by Grumoth** [comment]
Finally managed to reproduce and fix it, there was a lot of changes regarding gltf import structure and bone naming. Hope it works now.

**Comment by Malkverbena** [comment]
NIce job dude!!
